@echo off
echo ========================================
echo  ServingSync POS - Windows .exe Builder
echo ========================================
echo.

REM Change to the directory where this .bat file is located
cd /d "%~dp0"

echo Current directory: %cd%
echo.

REM ─── Step 0: Clean previous build output ───
echo Step 0: Cleaning previous build artifacts...
if exist "release" rmdir /s /q "release"
if exist ".next" rmdir /s /q ".next"
echo Cleaned.
echo.

echo Step 1: Installing dependencies...
call npm install
if %errorlevel% neq 0 (
    echo ERROR: npm install failed
    echo Make sure you have Node.js installed: https://nodejs.org
    pause
    exit /b 1
)

echo.
echo Step 2: Generating Windows .ico icon from SVG...
call node scripts/gen-icon.js
if %errorlevel% neq 0 (
    echo ERROR: Icon generation failed
    pause
    exit /b 1
)

echo.
echo Step 3: Generating Prisma client...
call npx prisma generate
if %errorlevel% neq 0 (
    echo ERROR: Prisma generate failed
    pause
    exit /b 1
)

echo.
echo Step 4: Building Next.js standalone...
call npm run build
if %errorlevel% neq 0 (
    echo ERROR: Next.js build failed
    pause
    exit /b 1
)

echo.
echo Step 5: Building Electron .exe installer...
call npx electron-builder --win --x64
if %errorlevel% neq 0 (
    echo ERROR: Electron build failed
    echo Trying alternative method (electron-packager)...
    call npx electron-packager . "ServingSync POS" --platform=win32 --arch=x64 --overwrite --prune=true --out=release --ignore="upload|scripts|dev.log|server.log|\.env$|release"
    if %errorlevel% neq 0 (
        echo ERROR: Both build methods failed
        pause
        exit /b 1
    )
)

echo.
echo ========================================
echo  BUILD COMPLETE!
echo ========================================
echo.
echo Your .exe is in the "release" folder.
echo   - "ServingSync POS Setup.exe"  (installer)
echo   - "release\win-unpacked\ServingSync POS.exe"  (portable)
echo.
echo NOTE: builder-effective-config.yaml is a normal debug log file
echo generated by electron-builder — it is NOT an error.
echo.
echo To run: Double-click "ServingSync POS Setup.exe"
echo.
echo First launch will ask for a license key.
echo Login: super@servingsync.com / admin123
echo.
pause
